name: resilience_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h458dff3_0
  - blosc=1.21.6=hfd34d9b_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cftime=1.6.5=py310h8f3aa81_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhcf101f3_2
  - double-conversion=3.3.1=he0c23c2_0
  - expat=2.7.4=hd7fb8db_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.17.1=hd47e2ca_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=hf297d47_2
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.14.0=hdade9fe_0
  - geotiff=1.7.4=h86c3423_2
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_hae35d4c_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.5=haf901d7_0
  - libarchive=3.8.1=gpl_h1ca5a36_100
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_3
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_18
  - libgdal-core=3.10.3=hb656e25_17
  - libglib=2.86.3=h9bccc14_0
  - libgomp=15.2.0=h8ee18e1_18
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - liblzma-devel=5.8.2=hfd05255_0
  - libnetcdf=4.9.3=nompi_ha45073a_102
  - libpng=1.6.55=h7351971_0
  - librttopo=1.1.0=h5ff11c1_19
  - libspatialindex=2.1.0=h518811d_0
  - libspatialite=5.1.0=h32e9a1a_15
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h550210a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - netcdf4=1.7.4=nompi_py310h0ae9510_102
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310h4987827_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310hed136d8_2
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pillow=11.3.0=py310hb3a2f59_3
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - proj=9.6.2=h7990399_2
  - pthread-stubs=0.4=h0e40799_1002
  - pyogrio=0.11.0=py310hf80745b_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.1=py310h61ea1ad_1
  - pyside6=6.9.2=py310h2d19612_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.2=ha0de62e_2
  - rasterio=1.4.3=py310h9f9a88e_2
  - requests=2.32.5=pyhcf101f3_1
  - rtree=1.4.1=pyh11ca60a_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.10.2=py310haa95532_0
  - shapely=2.1.2=py310h57f9f94_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.1=hda9a48d_0
  - statsmodels=0.14.6=py310h8f3aa81_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py310h29418f3_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.1=py310h29418f3_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.8.2=hb6c8415_0
  - xz-tools=5.8.2=hfd05255_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - altair==6.0.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - cdsapi==0.7.7
      - ecmwf-datastores-client==0.4.2
      - gitdb==4.0.12
      - gitpython==3.1.46
      - multiurl==0.3.7
      - narwhals==2.16.0
      - plotly==6.5.2
      - pyarrow==23.0.1
      - pydeck==0.9.1
      - smmap==5.0.2
      - streamlit==1.54.0
      - toml==0.10.2
      - watchdog==6.0.0
prefix: D:\COLLEGE\ANACONDA\envs\resilience_env
